# Generated by Django 4.2.4 on 2023-09-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_departments_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.departments'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
