# Generated by Django 4.2.4 on 2023-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_doctor_depart_alter_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
