# Generated by Django 4.2.4 on 2023-09-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_departments_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fee',
        ),
    ]
